services:
  php:
    #container_name: php_dev
    build:
      dockerfile: ./docker/Dockerfile-php
    environment:
      SYMFONY_VERSION: ${SYMFONY_VERSION:-7.1.*}
      PHP_VERSION: ${PHP_VERSION:-8.3}
      DATABASE_URL: mysql://${MYSQL_USER:-app}:${MYSQL_PASSWORD:-!ChangeMe!}@localhost:3306/${MYSQL_DATABASE:-app}?serverVersion=${MYSQL_VERSION:-8}&charset=utf8mb4
      networks: symfony
    volumes:
      - .:/var/www/html
  nginx:
    #container_name: nginx_dev
    build:
      dockerfile: ./docker/Dockerfile-nginx
    ports:
      # HTTPS
      - target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp
      # HTTPS
      - target: 443
        published: ${HTTPS_PORT:-443}
        protocol: tcp
    volumes:
      - .:/var/www/html
    depends_on:
      - php
    networks:
      - symfony
  database:
    image: mysql:${MYSQL_VERSION:-8}
    #container_name: mysql_dev
    environment:
      #MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: ${MYSQL_DATABASE:-app}
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_USER: ${MYSQL_USER:-app}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-!ChangeMe!}
    volumes:
      - database_data:/var/lib/mysql:rw
    ports:
      - "3306:3306"
    networks:
      - symfony
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 5
      start_period: 60s
volumes:
  database_data:

networks:
  symfony:
    driver: bridge