services:
  php:
    container_name: php_dev
    build:
      dockerfile: ./docker/Dockerfile-php
    environment:
      SYMFONY_VERSION: ${SYMFONY_VERSION:-7.1.*}
      PHP_VERSION: ${PHP_VERSION:-8.3}
    networks:
      - symfony
    volumes:
      - .:/var/www/html
  nginx:
    container_name: nginx_dev
    build:
      dockerfile: ./docker/Dockerfile-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/html
    depends_on:
      - php
    networks:
      - symfony
  database:
    image: mysql:8
    container_name: mysql_dev
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app_password
    volumes:
      - database_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - symfony
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 5
      start_period: 60s

volumes:
  database_data:

networks:
  symfony:
    driver: bridge