services:
  php:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-php
    env_file:
      - ./docker/.env.docker
    volumes:
      - .:/var/www/html
    networks:
      - symfony

  nginx:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-nginx
    env_file:
      - ./docker/.env.docker
    volumes:
      - .:/var/www/html
      - ./docker/nginx/dev/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/dev/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "${HTTP_PORT:-80}:80"
    depends_on:
      - php
    networks:
      - symfony

  mysql:
    image: mysql:${MYSQL_VERSION-8.4}
    restart: always
    env_file:
      - ./docker/.env.docker
    volumes:
      - database_data:/var/lib/mysql:rw
      - ./docker/scripts/db_test.sql:/docker-entrypoint-initdb.d/db_test.sql
    ports:
      - "3306:3306"
    networks:
      - symfony
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  database_data:

networks:
  symfony:
    driver: bridge