# Base PHP image
FROM php:8.3-fpm AS php_base

# Install system dependencies and PHP dependencies
RUN set -eux; \
    apt-get update && apt-get upgrade -y && \
    apt-get install -y --no-install-recommends \
        unzip \
        git \
        acl \
        file \
        gettext \
        libicu-dev \
        libzip-dev \
    && docker-php-ext-install \
        intl \
        pdo \
        pdo_mysql \
        zip \
    && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Install Composer.
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer

# Install Symfony CLI.
RUN curl -sS https://get.symfony.com/cli/installer | bash \
    && mv /root/.symfony*/bin/symfony /usr/local/bin/symfony \
    && rm -rf /root/.symfony*

# Copy entrypoint script and set permissions.
COPY ./docker/scripts/symfony-start.sh /usr/local/bin/symfony-start.sh
RUN chmod +x /usr/local/bin/symfony-start.sh

HEALTHCHECK --interval=15s --timeout=10s --start-period=30s --retries=10 CMD [ -f /tmp/healthy ] || exit 1
ENTRYPOINT ["/usr/local/bin/symfony-start.sh"]


#/*## Execute Entrypoint.
#
#
#CMD ["sh", "-c", "/usr/local/bin/symfony-start.sh && php-fpm"]
