# Base Nginx image
FROM nginx:alpine

# Copy Nginx configuration files
COPY ./docker/nginx/dev/default.conf /etc/nginx/conf.d/default.conf
COPY ./docker/nginx/dev/nginx.conf /etc/nginx/nginx.conf

# Expose port 80
EXPOSE 80