# Base PHP image
FROM php:8.3-fpm AS php_base

## Install system dependencies
RUN set -eux; \
    apt-get update; \
    apt-get upgrade -y; \
    apt-get install -y --no-install-recommends \
    unzip \
    git \
    acl \
    file \
    gettext \
    libicu-dev \
    libzip-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

## Configure PHP extensions
#RUN set -eux; \
#     docker-php-ext-configure gd --with-jpeg --with-freetype

## Install PHP extensions
RUN set -eux; \
    docker-php-ext-install \
    intl \
    pdo \
    pdo_mysql \
    zip


## Install Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

## Install Symfony CLI
RUN curl -sS https://get.symfony.com/cli/installer | bash \
    && mv /root/.symfony*/bin/symfony /usr/local/bin/symfony \
    && rm -rf /root/.symfony*

# Copy entrypoint script and set permissions
COPY ./docker/scripts/symfony-start.sh /usr/local/bin/symfony-start.sh
RUN chmod +x /usr/local/bin/symfony-start.sh

## Execute Entrypoint
CMD ["sh", "-c", "/usr/local/bin/symfony-start.sh && php-fpm"]
